GET http://localhost:3001/

###
GET http://localhost:3001/api/post

###

GET http://localhost:3001/api/post/1

###

POST http://localhost:3001/api/post/
Content-Type: application/json

{
    "username": "mona",
    "text": "Goodbye"
    
}
###

PUT http://localhost:3001/api/post
Content-Type: application/json

{
    "username": "LiNd4",
    "text": "_h3lLo0_w0rLD_"
}

###
DELETE http://localhost:3001/api/post/608179d1f00a5c4cbbb13951