GET http://localhost:4000/

###
GET http://localhost:4000/api/post

###

GET http://localhost:4000/api/post/1

###

POST http://localhost:4000/api/post/
Content-Type: application/json

{
    "username": "kalle",
    "text": "Goodbye"
}

###

PUT http://localhost:4000/api/post/6082b60b24a3c921ddcc2cfa
Content-Type: application/json

{
    "username": "mona",
    "text": "_h3lLo0_w0rLD_ hejhejehej"
}

###
DELETE http://localhost:4000/api/post/608179d1f00a5c4cbbb13951