GET http://localhost:3001/api/user/

###
POST http://localhost:3001/api/user/register
Content-Type: application/json

{
    "username": "mona",
    "password": "123456"
}

###
POST http://localhost:3001/api/user/login
Content-Type: application/json

{
    "username": "mona",
    "password": "123456"
}

###
DELETE http://localhost:3001/api/user/logout